version: '3'
services:
  geoserver:
    image: docker.osgeo.org/geoserver:2.24.1
    volumes:
      - ./docker/geoserver_data:/geoserver_data/data
      - ./docker/geowebcache_data:/geowebcache_data
    ports:
      - 8089:8080
    environment:
      JAVA_OPTS: "-Xms256m -Xmx512m"
      INSTALL_EXTENSIONS: "true"
      STABLE_EXTENSIONS: "importer"
