---

# This docker-compose file is required to bind ports in development,
# since binding ports in regular compose file will ruin scaling
# in production. Due to how `ports` directive is merged with two files.
#
# This file is ignored in production, but
# it is automatically picked up in development with:
#
#  $ docker-compose up

version: "3.8"
services:

  mysqldb:
    image: mysql:8.0.29
    restart: unless-stopped
    env_file: ./config/.env
    networks:
      - appnet
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3307:3306"

  djapp:
    depends_on:
      - mysqldb
    ports:
      # We only bind ports directly in development:
      - "8000:8000"
    volumes:
      # We only mount source code in development:
      - .:/code
    environment:
      DJANGO_DATABASE_HOST: mysqldb
      DJANGO_DATABASE_PORT: 3306
