# Generated by Django 4.2.6 on 2024-10-03 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis_map', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GisMapView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.PositiveIntegerField(default=0)),
                ('updated_by', models.PositiveIntegerField(default=0)),
                ('view_point_id', models.PositiveIntegerField(db_index=True)),
                ('zoom', models.FloatField(default=15)),
                ('max_zoom', models.FloatField()),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
            ],
            options={
                'db_table': 'gis_map_views',
            },
        ),
    ]
