# Generated by Django 4.2.6 on 2024-04-15 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis_map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gisviewpoint',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='gisviewpoint',
            name='name',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
