# Generated by Django 4.2.6 on 2024-05-11 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis_map', '0002_gisviewpoint_description_gisviewpoint_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='gisviewpointcamera',
            name='description',
            field=models.TextField(default='', null=True),
        ),
    ]
