# Generated by Django 4.2.6 on 2024-10-03 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gis_map', '0002_gismapview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gismapview',
            name='max_zoom',
        ),
    ]
