# Generated by Django 4.2.6 on 2023-10-08 08:12

import dirtyfields.dirtyfields
from django.db import migrations, models
import src.Apps.base.models.cache
import src.Apps.base.models.custom_data_types
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('deleted_by', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, null=True)),
                ('created_by', models.PositiveIntegerField(default=0)),
                ('updated_by', models.PositiveIntegerField(default=0)),
                ('company_id', models.PositiveIntegerField(db_index=True, default=0)),
                ('name', models.CharField(db_index=True, default='', max_length=255)),
                ('status', src.Apps.base.models.custom_data_types.TinyIntegerField(default=0)),
                ('base_id', models.PositiveIntegerField(db_index=True, default=0)),
            ],
            options={
                'db_table': 'ai_approval_flows',
            },
            bases=(models.Model, dirtyfields.dirtyfields.DirtyFieldsMixin, src.Apps.base.models.cache.MasterCacheHandler),
        ),
        migrations.CreateModel(
            name='ApprovalRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('deleted_by', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, null=True)),
                ('created_by', models.PositiveIntegerField(default=0)),
                ('updated_by', models.PositiveIntegerField(default=0)),
                ('approval_rule_group_id', models.PositiveIntegerField(db_index=True, default=0)),
                ('targeting_rule', src.Apps.base.models.custom_data_types.TinyIntegerField(default=0)),
                ('match', src.Apps.base.models.custom_data_types.TinyIntegerField(null=True)),
            ],
            options={
                'db_table': 'ai_approval_rules',
            },
            bases=(models.Model, dirtyfields.dirtyfields.DirtyFieldsMixin, src.Apps.base.models.cache.MasterCacheHandler),
        ),
        migrations.CreateModel(
            name='ApprovalRuleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('deleted_by', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, null=True)),
                ('created_by', models.PositiveIntegerField(default=0)),
                ('updated_by', models.PositiveIntegerField(default=0)),
                ('approval_flow_id', models.PositiveIntegerField(db_index=True, default=0)),
                ('item_connect_operator', src.Apps.base.models.custom_data_types.TinyIntegerField(null=True)),
            ],
            options={
                'db_table': 'ai_approval_rule_groups',
            },
            bases=(models.Model, dirtyfields.dirtyfields.DirtyFieldsMixin, src.Apps.base.models.cache.MasterCacheHandler),
        ),
    ]
