# `nitpick` specific configuration.
# `nitpick` ensures that you have the same configuration
# in your own project.

# Make sure to install it with:
# `pip install nitpick`

# See: https://nitpick.readthedocs.io/en/latest/

[nitpick.files.present]
    "pyproject.toml" = "Install poetry and run 'poetry init' to create it"
