# Generated by Django 4.2.6 on 2024-04-07 16:28

from django.db import migrations, models
import src.Apps.base.models.custom_data_types
import src.Apps.user.constants.system_attribute_key


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.PositiveIntegerField(default=0)),
                ('updated_by', models.PositiveIntegerField(default=0)),
                ('value', models.CharField(blank=True, default='', max_length=960, null=True)),
                ('attribute_key_id', models.PositiveIntegerField(db_index=True)),
                ('user_id', models.PositiveIntegerField(db_index=True)),
            ],
            options={
                'db_table': 'user_attributes',
            },
        ),
        migrations.CreateModel(
            name='UserAttributeKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.PositiveIntegerField(default=0)),
                ('updated_by', models.PositiveIntegerField(default=0)),
                ('label', models.CharField(max_length=255)),
                ('key_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('is_default', models.BooleanField(default=False)),
                ('category', src.Apps.base.models.custom_data_types.TinyIntegerField(default=2)),
                ('status', src.Apps.base.models.custom_data_types.TinyIntegerField(default=1)),
                ('privacy_setting', src.Apps.base.models.custom_data_types.TinyIntegerField(default=1)),
                ('attribute_data_type', src.Apps.base.models.custom_data_types.PositiveTinyIntegerField(default=1)),
                ('attribute_type', src.Apps.base.models.custom_data_types.TinyIntegerField(default=src.Apps.user.constants.system_attribute_key.SystemAttributeKeyType['USER'])),
            ],
            options={
                'db_table': 'user_attribute_keys',
            },
        ),
    ]
