class ValidationErr:
    REQUIRED = dict(code=1100, message="{0} is required.")
    NULL = dict(code=1101, message="{0} may not be null.")
    EMPTY = dict(code=1102, message="{0} may not be empty.")
    UNIQUE = dict(code=1103, message="{0} must be unique.")
    ALREADY_IN_USE = dict(code=1104, message="{0} already in use.")
    DOES_NOT_EXIST = dict(code=1105, message="{0} does not exist.")
    MAX_LENGTH = dict(code=1106, message="{0} must be less than or equal to {1} characters.")
    MIN_LENGTH = dict(code=1107, message="{0} must be at least {1} characters.")
    MAX_STRING_LENGTH = dict(code=1108, message="String value too large.")
    MAX_VALUE = dict(code=1109, message="{0} must be less than or equal to {1}.")
    MIN_VALUE = dict(code=1110, message="{0} must be greater than or equal to {1}.")
    MAX_DECIMAL_VALUE = dict(code=1111, message="{0} is invalid.")
    DATE = dict(code=1112, message="{0} must be a date.")
    DATETIME = dict(code=1113, message="{0} must be a datetime.")
    NOT_A_LIST = dict(code=1114, message="{0} must be a list.")
    NOT_A_DICT = dict(code=1115, message="{0} must be a dict.")
    INVALID = dict(code=1116, message="{0} is invalid.")
    INVALID_BOOLEAN = dict(code=1117, message="{0} is not a valid boolean.")
    INVALID_EMAIL = dict(code=1118, message="{0} is not a valid email address.")
    INVALID_REGEX = dict(code=1119, message="{0} does not match the required pattern.")
    INVALID_SLUG = dict(code=1120, message="{0} is invalid slug.")
    INVALID_URL = dict(code=1121, message="{0} is invalid URL.")
    INVALID_UUID = dict(code=1122, message="{0} is invalid UUID.")
    INVALID_IP_ADDRESS = dict(code=1123, message="{0} must be a valid IPv4 or IPv6 address.")
    INVALID_INTEGER = dict(code=1124, message="{0} is invalid integer.")
    INVALID_NUMBER = dict(code=1125, message="{0} is invalid number.")
    INVALID_DATE = dict(code=1126, message="{0} is invalid date format.")
    INVALID_TIME = dict(code=1127, message="{0} is invalid time format.")
    INVALID_DATETIME = dict(code=1128, message="{0} is invalid datetime format.")
    INVALID_DURATION = dict(code=1129, message="{0} is invalid duration format.")
    INVALID_CHOICE = dict(code=1130, message="{0} is invalid choice.")
    INVALID_FILE = dict(code=1131, message="{0} is not a valid file.")
    INVALID_FILE_PATH = dict(code=1132, message="{0} is not a valid file path.")
    INVALID_IMAGE = dict(code=1133, message="{0} is not a valid image.")
    INVALID_JSON = dict(code=1134, message="{0} must be valid JSON.")
    NO_FILE_NAME = dict(code=1135, message="No filename could be determined.")
    REQUIRED_FILE = dict(code=1136, message="No file was submitted.")
    EMPTY_FILE = dict(code=1137, message="The submitted file is empty.")
    EMPTY_LIST = dict(code=1138, message="This list may not be empty.")
    EMPTY_CHOICE = dict(code=1139, message="This selection may not be empty.")
    UNIQUE_SET = dict(code=1140, message="The fields {0} must make a unique set.")
