---
name: "CI (Testing 🧪)"

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - rc
      - dev/*
      - test/*
concurrency:
  group: test-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  CheckCodeQuality:
    if: github.event.pull_request.merged == false
    runs-on: [self-hosted, "tool-runner"]
    timeout-minutes: 30
    strategy:
      matrix:
        os: [ubuntu-20.04]

    steps:
      - name: Checkout source code 📥
        uses: actions/checkout@v3
      - name: Run checks 🧪
        run: ./bin ci:docker-test

  DraftRelease:
    if: success() && github.event_name != 'pull_request'
    needs: CheckCodeQuality
    uses: ./.github/workflows/pre-release.yml
    with:
      is_draft_release: true
