---
name: "Dockerfile Linter"

on:
  push:
    branches:
      - master
      - main
    paths:
      - 'docker/django/Dockerfile'
  pull_request:
    paths:
      - 'docker/django/Dockerfile'
  workflow_dispatch:

concurrency:
  group: hadolint-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  Dockerfile-Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hadolint/hadolint-action@v2.1.0
        with:
          dockerfile: 'docker/django/Dockerfile'
          failure-threshold: style
          verbose: true
